stages:
  - deploy

variables:
  DEPLOY_SERVER: "52.237.96.127"
  DEPLOY_USER: "jomla-admin"
  DEPLOY_PASSWORD: "6D!S!Wf8Hz7qqyG"
  DEPLOY_PATH: "/var/www"
  REPO_URL: "https://github.com/wasabid3v/intranet-tourism.git"
  TRIGGER_TOKEN: "glptt-10d63d0b72b82d1d999e5838e2bd324e0c62c6ef"  # Replace with your actual trigger token

deploy:
  stage: deploy
  before_script:
    - 'which sshpass || (apt-get update -y && apt-get install sshpass -y)'
  script:
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "sudo rm -rf $DEPLOY_PATH/intranet-tourism"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "sudo mkdir -p $DEPLOY_PATH/intranet-tourism && sudo chown $DEPLOY_USER:$DEPLOY_USER $DEPLOY_PATH/intranet-tourism"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "git clone --branch main https://github.com/wasabid3v/intranet-tourism.git $DEPLOY_PATH/intranet-tourism"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "sudo cp /home/jomla-admin/workspace/intranet-tourism/.env $DEPLOY_PATH/intranet-tourism/.env"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH/intranet-tourism && sudo chown -R $DEPLOY_USER:$DEPLOY_USER storage bootstrap/cache"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH/intranet-tourism && sudo chmod -R 775 storage bootstrap/cache"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH/intranet-tourism && sudo chown $DEPLOY_USER:$DEPLOY_USER .env"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH/intranet-tourism && sudo -u $DEPLOY_USER composer install"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH/intranet-tourism && sudo -u $DEPLOY_USER php artisan key:generate --force"
    # - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH/intranet-tourism && sudo -u $DEPLOY_USER php artisan migrate:fresh --seed --force"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "sudo chown -R www-data:www-data $DEPLOY_PATH/intranet-tourism/storage"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "sudo chown -R www-data:www-data $DEPLOY_PATH/intranet-tourism/bootstrap/cache"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "sudo chmod -R 775 $DEPLOY_PATH/intranet-tourism/storage"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "sudo chmod -R 775 $DEPLOY_PATH/intranet-tourism/bootstrap/cache"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH/intranet-tourism && sudo -u $DEPLOY_USER php artisan storage:link"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH/intranet-tourism && sudo -u $DEPLOY_USER npm install"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH/intranet-tourism && sudo -u $DEPLOY_USER npm run build"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "sudo systemctl restart nginx"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "sudo systemctl restart artisan-queue"
    - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER "sudo systemctl restart artisan-reverb"
  only:
    - main
