version: "3.8"
services:
    app:
        image: bonkboykz/intranet-tourism:latest
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        env_file:
            - .env
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - laravel

    db:
        image: postgres:15
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=laravel
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=dilliponz123
        volumes:
            - postgres_data:/var/lib/postgresql/data

    node:
        image: node:20
        container_name: laravel_node
        working_dir: /var/www
        volumes:
            - ./:/var/www

volumes:
    postgres_data:
