version: "3.8"
services:
    web:
        image: ghcr.io/enzeetech/jomla-tourism:latest
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - ./storage:/app/storage/app
            - ./seed-data:/app/seed
        env_file:
            - .env
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
            - soketi
            - meilisearch
        user: "${UID}:${GID}"

    worker:
        image: ghcr.io/enzeetech/jomla-tourism-worker:latest
        container_name: laravel_worker
        restart: on-failure
        command: php artisan queue:work
        depends_on:
            - web
            - db
            - redis
            - soketi
            - meilisearch
        volumes:
            - ./worker-storage:/var/www/storage
        user: "${UID}:${GID}"

    db:
        image: postgres:15
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=laravel
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        user: "${UID}:${GID}"

    soketi:
        image: quay.io/soketi/soketi:latest-16-alpine
        container_name: laravel_soketi
        restart: unless-stopped
        ports:
            - "6001:6001"
        environment:
            - SOKETI_DEFAULT_APP_ID=1
            - SOKETI_DEFAULT_APP_KEY=secret
            - SOKETI_DEFAULT_APP_SECRET=secret
        volumes:
            - soketi-data:/var/www/soketi
        user: "${UID}:${GID}"

    redis:
        image: bitnami/redis:latest
        container_name: laravel_redis
        ports:
            - "6379:6379"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - redis-data:/bitnami/redis/data
        user: "${UID}:${GID}"

    meilisearch:
        image: getmeili/meilisearch:v1.10
        container_name: laravel_meilisearch
        restart: unless-stopped
        ports:
            - "7700:7700"
        environment:
            - MEILI_MASTER_KEY=masterKey
            - MEILI_HTTP_ADDR=0.0.0.0:7700
        volumes:
            - meilisearch-data:/data.ms
        user: "${UID}:${GID}"

volumes:
    postgres-data:
    soketi-data:
    redis-data:
    meilisearch-data:
