version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: .nixpacks/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage:/app/storage/app
        env_file:
            - .env
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
            - soketi

    worker:
        build:
            context: .
            dockerfile: .nixpacks/Dockerfile
        container_name: laravel_worker
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage:/app/storage/app
        command: php artisan queue:work
        env_file:
            - .env
        depends_on:
            - app
            - db
            - redis
            - soketi

    db:
        image: postgres:15
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=laravel
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data

    soketi:
        image: quay.io/soketi/soketi:latest-16-alpine
        container_name: laravel_soketi
        restart: unless-stopped
        ports:
            - "6001:6001"

    redis:
        image: bitnami/redis:latest
        container_name: laravel_redis
        ports:
            - "6379:6379"

    meilisearch:
        image: getmeili/meilisearch:v1.10
        container_name: laravel_meilisearch
        restart: unless-stopped
        ports:
            - "7700:7700"

volumes:
    postgres_data:
