providers = ["...", "php"]

[phases.build]
cmds = [
    '...',
    "echo \"<<<<<<<<<<<<< CHANGING THE PHP INI >>>>>>>>>>>>>>\"",
    "PHP_INI_PATH=$(php -i | grep '/php.ini' | awk '{print $6}')",
    "./setup_limits.sh",
]
