providers = ["...", "php"]

[phases.setup]
nixPkgs = ['...', 'php82Extensions.gd']

[phases.build]
cmds = [
    '...',
    "php artisan optimize",
    "php artisan migrate",
    "php artisan storage:link",
    "./setup_limits.sh",
]
