providers = ["...", "php"]

[phases.setup]
nixPkgs = ['...', 'php82Extensions.gd']

[phases.build]
cmds = [
    '...',
    # TODO: When modules clean up done, uncomment below
    # "php artisan optimize",
    # "php artisan migrate",
    "php artisan storage:link",
    "./setup_limits.sh",
]
