[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"
nixpacksVersion = "1.28.1"

[deploy]
region = "asia-southeast1"
runtime = "V2"
numReplicas = 3
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
