name: Build and push docker image

on:
    push:
        branches:
            - dev2

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        env:
            GH_USER: ${{ secrets.GH_USER }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            NAME: jomla-tourism
            TAG: ${{ github.sha }}
            TAG_LATEST: latest
            GHCR_REPO: ghcr.io/enzeetech/jomla-tourism

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build and push Docker image
              run: |
                  export GHCR_TAG=$GHCR_REPO:$TAG
                  export GHCR_TAG_LATEST=$GHCR_REPO:$TAG_LATEST

                  echo $GHCR_TAG
                  echo $GHCR_TAG_LATEST

                  mv .env.example .env

                  docker build -t "$GHCR_TAG" -t "$GHCR_TAG_LATEST" -f .nixpacks/Dockerfile .

                  docker login ghcr.io -u "$GH_USER" -p "$GH_TOKEN"
                  docker push "$GHCR_TAG"
                  docker push "$GHCR_TAG_LATEST"
