name: Build and push docker image

on:
    push:
        branches:
            - dev2

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        env:
            GH_USER: ${{ secrets.GH_USER }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            NAME: jomla-tourism
            TAG: ${{ github.sha }}
            TAG_LATEST: latest
            GHCR_REPO: ghcr.io/enzeetech/jomla-tourism
            UPLOAD_MAX_FILESIZE: "1024M"
            POST_MAX_SIZE: "1024M"
            MEMORY_LIMIT: "2048M"
            NIXPACKS_PHP_ROOT_DIR: "/app/public"
            APP_NAME: Jomla Tourism
            APP_ENV: production
            APP_KEY: base64:your-app-key
            APP_DEBUG: false
            APP_TIMEZONE: UTC
            APP_URL: https://jomla-stag.sociodev.com.my
            VITE_BASE_URL: https://jomla-stag.sociodev.com.my
            SANCTUM_STATEFUL_DOMAINS: jomla-stag.sociodev.com.my
            APP_LOCALE: "en"
            APP_FALLBACK_LOCALE: "en"
            APP_FAKER_LOCALE: "en_US"
            APP_MAINTENANCE_DRIVER: "file"
            APP_MAINTENANCE_STORE: "database"
            BCRYPT_ROUNDS: "12"
            LOG_CHANNEL: "stack"
            LOG_STACK: "single"
            LOG_DEPRECATIONS_CHANNEL: "null"
            LOG_LEVEL: "debug"
            DB_CONNECTION: "pgsql"
            DB_HOST: "localhost"
            DB_PORT: 5432
            DB_DATABASE: "your-dabase"
            DB_USERNAME: "your-user"
            DB_PASSWORD: "your-password"
            SESSION_DRIVER: "redis"
            SESSION_LIFETIME: "120"
            SESSION_ENCRYPT: "false"
            SESSION_PATH: "/"
            SESSION_DOMAIN: "null"
            SESSION_LOCK: "true"
            FILESYSTEM_DISK: "local"
            QUEUE_CONNECTION: "redis"
            CACHE_STORE: "redis"
            CACHE_PREFIX: ""
            REDIS_CLIENT: "predis"
            REDIS_HOST: "redis"
            REDIS_PASSWORD: "your-password"
            REDIS_PORT: "6379"
            REDIS_URL: "redis://redis:6379"
            REDIS_USERNAME: "redis"
            MAIL_MAILER: "log"
            MAIL_HOST: "127.0.0.1"
            MAIL_PORT: "2525"
            MAIL_USERNAME: "null"
            MAIL_PASSWORD: "null"
            MAIL_ENCRYPTION: "null"
            MAIL_FROM_ADDRESS: "hello@example.com"
            MAIL_FROM_NAME: "Laravel"
            AWS_ACCESS_KEY_ID: ""
            AWS_SECRET_ACCESS_KEY: ""
            AWS_DEFAULT_REGION: "us-east-1"
            AWS_BUCKET: ""
            AWS_USE_PATH_STYLE_ENDPOINT: "false"
            BROADCAST_CONNECTION: "pusher"
            PUSHER_APP_ID: "1"
            PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
            PUSHER_APP_SECRET: "secret"
            PUSHER_HOST: "soketi"
            PUSHER_PORT: "6001"
            PUSHER_SCHEME: "http"
            PUSHER_APP_CLUSTER: "mt1"
            VITE_PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
            VITE_PUSHER_HOST: https://jomla-stag.sociodev.com.my
            VITE_PUSHER_PORT: "6001"
            VITE_PUSHER_SCHEME: "http"
            VITE_PUSHER_APP_CLUSTER: "mt1"
            AZURE_CLIENT_ID: "your-azure-client-id"
            AZURE_CLIENT_SECRET: "your-azure-client-secret"
            AZURE_REDIRECT_URI: https://intranet-tourism.test/auth/azure/callback
            AZURE_TENANT_ID: "6223e1af-a146-4247-abcc-f04ad29fa785"
            PROXY: ""
            PORT: "8000"
            IS_LARAVEL: "true"
            SCOUT_DRIVER: "meilisearch"
            MEILISEARCH_HOST: "http://meilisearch:7700"
            MEILISEARCH_KEY: "your-password"
            SCOUT_QUEUE: "true"

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build and push Docker image
              run: |
                  export GHCR_TAG=$GHCR_REPO:$TAG
                  export GHCR_TAG_LATEST=$GHCR_REPO:$TAG_LATEST

                  echo $GHCR_TAG
                  echo $GHCR_TAG_LATEST

                  # place variables into the .env file
                  printenv | awk -F= '{print $1"="$2}' > .env

                  docker build -t "$GHCR_TAG" -t "$GHCR_TAG_LATEST" -f .nixpacks/Dockerfile .

                  docker login ghcr.io -u "$GH_USER" -p "$GH_TOKEN"
                  docker push "$GHCR_TAG"
                  docker push "$GHCR_TAG_LATEST"
    deploy:
        needs: build-and-push
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Enter the server
              uses: appleboy/ssh-action@v1.1.0
              with:
                  host: ${{ secrets.DEPLOY_SERVER }}
                  username: ${{ secrets.DEPLOY_USER }}
                  password: ${{ secrets.DEPLOY_PASSWORD }}
                  port: ${{ secrets.DEPLOY_PORT }} # default is 22
                  script: |
                      cd /home/${{ secrets.DEPLOY_USER }}/intranet-tourism-app
                      docker pull ghcr.io/enzeetech/jomla-tourism:latest
                      docker compose down
                      docker compose up -d

                      # migrate database
                      docker exec laravel_app php /app/artisan migrate --force
